name: Trigger-All-Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * 5

jobs:
  Taiyi-ImmortalWrt:
    uses: ./.github/workflows/Taiyi-ImmortalWrt.yml

  x86-64-ImmortalWrt:
    uses: ./.github/workflows/x86-64-ImmortalWrt.yml
